In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("house_sale.csv", on_bad_lines="skip", encoding = "utf-8", engine = "python")
df

,id_x,rel_url,estate_rel_url_x,datetime_scrape_x,price,currency_x,location,attributes,city_when,city,...,Mərtəbə,Otaq sayı,Sahə,Torpaq sahəsi,Təmir,Çıxarış,İpoteka,estate_details_id_y,estate_rel_url,extra_info
0,5df36281-6dc6-4d5d-89a7-5fcfa86f7608,/alqi-satqi?page=174,/items/4521724,2024-10-05 22:07:37.60613+00,499999.0,AZN,Səbail r.,"4 otaqlı, 145 m², 7/9 mərtəbə","Bakı, dünən 23:52",bakı,...,7 / 9,4.0,145 m²,NaN,var,var,NaN,92e82ea2-e1f3-4c2d-a284-151efd99281e,/items/4521724,Şəhidlər xiyabanı * Dağüstü parkı * Səbail r.
1,883e20f0-8872-49a5-8b4b-63b8301b5f8f,/alqi-satqi?page=250,/items/4669294,2024-10-05 22:07:37.60613+00,77000.0,AZN,Biləcəri q.,"4 otaqlı, 90 m²","Bakı, dünən 23:56",bakı,...,NaN,4.0,90 m²,1.3 sot,var,yoxdur,NaN,505eaf81-6bc8-4094-9b00-aa82066548ee,/items/4669294,Binəqədi r.* Biləcəri q.
2,55c36fb1-a3af-476e-ba17-a81f6795be8d,/alqi-satqi?page=250,/items/4669293,2024-10-05 22:07:37.60613+00,92000.0,AZN,İnşaatçılar m.,"3 otaqlı, 60 m²","Bakı, dünən 23:55",bakı,...,NaN,3.0,60 m²,0.1 sot,var,var,NaN,fa63b201-999d-43b5-a61a-778d9d79a6c6,/items/4669293,İnşaatçılar m.* Yasamal r.
3,acf1aa8d-a46a-40f5-b6f2-f7a449569337,/alqi-satqi?page=250,/items/4647811,2024-10-05 22:07:37.60613+00,95000.0,AZN,Qaraçuxur q.,130 m²,"Bakı, dünən 23:55",bakı,...,NaN,NaN,130 m²,NaN,var,var,var,5db56980-05cc-4925-b55b-f58fb3f4d2b6,/items/4647811,Suraxanı r.* Qaraçuxur q.
4,22d840df-9283-4112-bc71-7432511fc776,/alqi-satqi?page=250,/items/4638863,2024-10-05 22:07:37.60613+00,220000.0,AZN,Əhmədli m.,"3 otaqlı, 100 m², 15/16 mərtəbə","Bakı, dünən 23:52",bakı,...,15 / 16,3.0,100 m²,NaN,var,var,NaN,d71cf9a9-86dd-4162-b540-6252a8659a09,/items/4638863,Əhmədli m.* Xalqlar Dostluğu m.* Xətai r.* Əhm...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100770,b033ac14-d674-48a7-bc5c-3057bce7dd89,/alqi-satqi?page=296,/items/4774188,2024-11-19 20:46:55.308758,170000.0,AZN,Binəqədi q.,"6 otaqlı, 250 m²","Bakı, dünən 17:09",bakı,...,NaN,6.0,250 m²,3.5 sot,var,yoxdur,NaN,46eb114c-6b59-414d-8c40-fc211190ff46,/items/4774188,Binəqədi r.* Binəqədi q.
100771,b614e043-2712-4eb8-9a1e-723ed81ee489,/alqi-satqi?page=296,/items/3921717,2024-11-19 20:46:55.308758,520000.0,AZN,Mərdəkan q.,"4 otaqlı, 220 m²","Bakı, dünən 17:08",bakı,...,NaN,4.0,220 m²,11 sot,var,var,var,9bb02fc6-4f69-4f3e-95b3-2049e968e086,/items/3921717,Xəzər r.* Mərdəkan q.
100772,633d83f9-3a32-43fa-b089-b6c7085108a1,/alqi-satqi?page=296,/items/3933573,2024-11-19 20:46:55.308758,650000.0,AZN,Mərdəkan q.,"5 otaqlı, 350 m²","Bakı, dünən 17:08",bakı,...,NaN,5.0,350 m²,7 sot,var,var,var,29b3333e-e695-4cb6-bf75-f7f22225712d,/items/3933573,Xəzər r.* Mərdəkan q.
100773,ed8c1be0-b5a2-48a7-ba56-8d9e8389bb75,/alqi-satqi?page=296,/items/4774186,2024-11-19 20:46:55.308758,310000.0,AZN,20 Yanvar m.,"3 otaqlı, 130 m², 4/19 mərtəbə","Bakı, dünən 17:08",bakı,...,4 / 19,3.0,130 m²,NaN,var,var,var,cfa88cfc-75a3-4657-8822-b11c82483164,/items/4774186,20 Yanvar m.* Yasamal r.
100774,e85db6c0-141d-44a3-a078-dcb4a4641091,/alqi-satqi?page=296,/items/4655312,2024-11-19 20:46:55.308758,165000.0,AZN,Nərimanov r.,"2 otaqlı, 55 m², 13/15 mərtəbə","Bakı, dünən 17:17",bakı,...,13 / 15,2.0,55 m²,NaN,var,yoxdur,NaN,1af4df10-8bfe-4d29-8964-9d8533cd3883,/items/4655312,Şərq bazarı * Nərimanov r.

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100775 entries, 0 to 100774
Data columns (total 51 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id_x                 100775 non-null  object
 1   rel_url              100775 non-null  object
 2   estate_rel_url_x     100775 non-null  object
 3   datetime_scrape_x    100775 non-null  object
 4   price                100775 non-null  float64
 5   currency_x           100775 non-null  object
 6   location             100775 non-null  object
 7   attributes           100775 non-null  object
 8   city_when            100775 non-null  object
 9   city                 100775 non-null  object
 10  day_x                100775 non-null  object
 11  hour_x               100775 non-null  object
 12  repair               81612 non-null   object
 13  vip                  8596 non-null    object
 14  featured             3149 non-null    object
 15  products_label       72630 non-null   object
 16  bill_of_sale         79565 non-null   object
 17  mortgage             32939 non-null   object
 18  img_url              100775 non-null  object
 19  id_y                 100775 non-null  object
 20  estate_id            100775 non-null  object
 21  estate_rel_url_y     100775 non-null  object
 22  datetime_scrape_y    100775 non-null  object
 23  description          100510 non-null  object
 24  unit_price           75996 non-null   object
 25  total_price          100775 non-null  float64
 26  currency_y           100775 non-null  object
 27  owner_name           100118 non-null  object
 28  owner_title          100118 non-null  object
 29  shop_name            72018 non-null   object
 30  shop_title           72018 non-null   object
 31  address              100775 non-null  object
 32  lat                  100775 non-null  float64
 33  lng                  100775 non-null  float64
 34  updated              100775 non-null  object
 35  views                100775 non-null  int64
 36  day_y                100775 non-null  object
 37  hour_y               15631 non-null   object
 38  estate_details_id_x  100775 non-null  object
 39  Binanın növü         154 non-null     object
 40  Kateqoriya           100775 non-null  object
 41  Mərtəbə              75996 non-null   object
 42  Otaq sayı            91363 non-null   float64
 43  Sahə                 100775 non-null  object
 44  Torpaq sahəsi        15571 non-null   object
 45  Təmir                94774 non-null   object
 46  Çıxarış              100775 non-null  object
 47  İpoteka              32939 non-null   object
 48  estate_details_id_y  100775 non-null  object
 49  estate_rel_url       100775 non-null  object
 50  extra_info           100775 non-null  object
dtypes: float64(5), int64(1), object(45)
memory usage: 39.2+ MB

In [4]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
price,100775.0,342355.737395,2.042627e+06,11.000000,145000.00000,218000.000000,338000.000000,6.000000e+08
total_price,100775.0,342355.267040,2.042627e+06,11.000000,145000.00000,218000.000000,338000.000000,6.000000e+08
lat,100775.0,40.410846,8.319323e-02,32.689217,40.38190,40.397219,40.420578,4.177469e+01
lng,100775.0,49.886371,2.650083e-01,12.591688,49.81647,49.852867,49.948995,5.034106e+01
views,100775.0,700.065185,1.680673e+03,23.000000,99.00000,254.000000,680.000000,1.134580e+05
Otaq sayı,91363.0,3.133468,1.372981e+00,1.000000,2.00000,3.000000,4.000000,2.000000e+01

In [7]:
def preview(dataframe):
    print('Shape')
    print(dataframe.shape)
    print()
    print('Info')
    dataframe.info()
    print()
    print('Is Null Sum')
    print(dataframe.isnull().sum())
    print()
    print('Duplicates')
    print(dataframe.duplicated().sum())
preview(df)

Shape
(100775, 51)

Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100775 entries, 0 to 100774
Data columns (total 51 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id_x                 100775 non-null  object
 1   rel_url              100775 non-null  object
 2   estate_rel_url_x     100775 non-null  object
 3   datetime_scrape_x    100775 non-null  object
 4   price                100775 non-null  float64
 5   currency_x           100775 non-null  object
 6   location             100775 non-null  object
 7   attributes           100775 non-null  object
 8   city_when            100775 non-null  object
 9   city                 100775 non-null  object
 10  day_x                100775 non-null  object
 11  hour_x               100775 non-null  object
 12  repair               81612 non-null   object
 13  vip                  8596 non-null    object
 14  featured             3149 non-null    object
 15  products_label       72630 non-null   object
 16  bill_of_sale         79565 non-null   object
 17  mortgage             32939 non-null   object
 18  img_url              100775 non-null  object
 19  id_y                 100775 non-null  object
 20  estate_id            100775 non-null  object
 21  estate_rel_url_y     100775 non-null  object
 22  datetime_scrape_y    100775 non-null  object
 23  description          100510 non-null  object
 24  unit_price           75996 non-null   object
 25  total_price          100775 non-null  float64
 26  currency_y           100775 non-null  object
 27  owner_name           100118 non-null  object
 28  owner_title          100118 non-null  object
 29  shop_name            72018 non-null   object
 30  shop_title           72018 non-null   object
 31  address              100775 non-null  object
 32  lat                  100775 non-null  float64
 33  lng                  100775 non-null  float64
 34  updated              100775 non-null  object
 35  views                100775 non-null  int64
 36  day_y                100775 non-null  object
 37  hour_y               15631 non-null   object
 38  estate_details_id_x  100775 non-null  object
 39  Binanın növü         154 non-null     object
 40  Kateqoriya           100775 non-null  object
 41  Mərtəbə              75996 non-null   object
 42  Otaq sayı            91363 non-null   float64
 43  Sahə                 100775 non-null  object
 44  Torpaq sahəsi        15571 non-null   object
 45  Təmir                94774 non-null   object
 46  Çıxarış              100775 non-null  object
 47  İpoteka              32939 non-null   object
 48  estate_details_id_y  100775 non-null  object
 49  estate_rel_url       100775 non-null  object
 50  extra_info           100775 non-null  object
dtypes: float64(5), int64(1), object(45)
memory usage: 39.2+ MB

Is Null Sum
id_x                        0
rel_url                     0
estate_rel_url_x            0
datetime_scrape_x           0
price                       0
currency_x                  0
location                    0
attributes                  0
city_when                   0
city                        0
day_x                       0
hour_x                      0
repair                  19163
vip                     92179
featured                97626
products_label          28145
bill_of_sale            21210
mortgage                67836
img_url                     0
id_y                        0
estate_id                   0
estate_rel_url_y            0
datetime_scrape_y           0
description               265
unit_price              24779
total_price                 0
currency_y                  0
owner_name                657
owner_title               657
shop_name               28757
shop_title              28757
address                     0
lat                         0
lng                         0
updated                     0
views                       0
day_y                       0
hour_y                  85144
estate_details_id_x         0
Binanın növü           100621
Kateqoriya                  0
Mərtəbə                 24779
Otaq sayı                9412
Sahə                        0
Torpaq sahəsi           85204
Təmir                    6001
Çıxarış                     0
İpoteka                 67836
estate_details_id_y         0
estate_rel_url              0
extra_info                  0
dtype: int64

Duplicates
0